# If you are interested in supporting this project, you can do so here:

github: [blackphoenix42]
# Other funding platforms (uncomment and add your details as needed):
# patreon: your-patreon-username
# open_collective: your-opencollective-username
# ko_fi: your-kofi-username
# tidelift: npm/your-package-name
# community_bridge: your-project-name
# liberapay: your-liberapay-username
# issuehunt: your-issuehunt-username
# otechie: your-otechie-username
# lfx_crowdfunding: your-crowdfunding-project-name
# custom: ['https://paypal.me/username', 'https://buymeacoffee.com/username']
