name: Lighthouse

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  lhci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install deps & build
        run: |
          npm ci
          npm run build --if-present || npx vite build

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v12
        with:
          configPath: lhci/lighthouserc.json
          runs: 1
          uploadArtifacts: true
          temporaryPublicStorage: true
