name: Lighthouse

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  lhci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install deps & build
        run: |
          npm ci

      # Workaround npm optional-deps quirk for Rollup on Linux
      - name: Patch Rollup native binary (Linux)
        if: runner.os == 'Linux'
        run: npm i --no-save --no-package-lock @rollup/rollup-linux-x64-gnu@^4

      - name: Build application
        run: npm run build --if-present || npx vite build

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v12
        with:
          configPath: lhci/lighthouserc.json
          runs: 1
          uploadArtifacts: true
          temporaryPublicStorage: true
